import { ENV } from './env.config';

export const JWT_CONFIG = {
    SECRET: ENV.JWT_SECRET,
    EXPIRES_IN: ENV.JWT_EXPIRES_IN,
    REFRESH_SECRET: ENV.REFRESH_TOKEN_SECRET,
    REFRESH_EXPIRES_IN: ENV.REFRESH_TOKEN_EXPIRES_IN,
};
